import os
import argparse
import shutil
import urllib.request
import zipfile
import numpy as np
import torch
import torch.nn as nn
import torchvision
import torchvision.transforms as transforms
import torchvision.models as tv_models
import random
from utils import get_dataset, get_network, epoch, get_time, ParamDiffAug

# ---------------------------------------------------------------------------
# Custom Dataset Wrapper for Unlearnable Examples
# ---------------------------------------------------------------------------
class PoisonedDataset(torch.utils.data.Dataset):
    def __init__(self, base_dataset, noise_path, perturb_type='samplewise'):
        self.base_dataset = base_dataset
        self.perturb_type = perturb_type
        
        print(f"Loading noise tensor from {noise_path}...")
        # Load the noise tensor generated by perturbation.py
        self.noise_tensor = torch.load(noise_path, map_location='cpu')
        
    def __len__(self):
        return len(self.base_dataset)

    def __getitem__(self, index):
        # Get the original image and label from the base dataset
        img, label = self.base_dataset[index]
        
        # Select the appropriate noise based on the generation method
        if self.perturb_type == 'samplewise':
            noise = self.noise_tensor[index]
        elif self.perturb_type == 'classwise':
            noise = self.noise_tensor[label]
        else:
            raise ValueError("perturb_type must be 'samplewise' or 'classwise'")
            
        # Ensure noise is a tensor and matches the image dtype/device
        if not isinstance(noise, torch.Tensor):
            noise = torch.tensor(noise)
            
        noise = noise.to(img.device).type(img.dtype)
        
        # Add the unlearnable noise to the image
        poisoned_img = img + noise
        
        # Note: Depending on your get_dataset() transforms, img might be in [0, 1] 
        # or normalized with mean/std. If it's simply ToTensor() [0, 1], you may 
        # want to clamp it to ensure valid pixel values:
        # poisoned_img = torch.clamp(poisoned_img, 0.0, 1.0)
        
        return poisoned_img, label


# ---------------------------------------------------------------------------
# ImageNet helpers
# ---------------------------------------------------------------------------

def train_epoch_plain(loader, net, optimizer, criterion, device):
    net.train()
    loss_sum, correct, total = 0.0, 0, 0
    for imgs, labels in loader:
        imgs, labels = imgs.to(device), labels.to(device)
        optimizer.zero_grad()
        out = net(imgs)
        loss = criterion(out, labels)
        loss.backward()
        optimizer.step()
        loss_sum += loss.item() * labels.size(0)
        correct  += out.argmax(1).eq(labels).sum().item()
        total    += labels.size(0)
    return loss_sum / total, correct / total


@torch.no_grad()
def eval_epoch_plain(loader, net, criterion, device):
    net.eval()
    loss_sum, correct, total = 0.0, 0, 0
    for imgs, labels in loader:
        imgs, labels = imgs.to(device), labels.to(device)
        out = net(imgs)
        loss = criterion(out, labels)
        loss_sum += loss.item() * labels.size(0)
        correct  += out.argmax(1).eq(labels).sum().item()
        total    += labels.size(0)
    return loss_sum / total, correct / total


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description='Train model on full dataset')
    parser.add_argument('--dataset',     type=str,   default='CIFAR10',  help='dataset (use ImageNet for ImageNet)')
    parser.add_argument('--model',       type=str,   default='ConvNet',  help='model (use ResNet18 for torchvision ResNet-18 on ImageNet)')
    parser.add_argument('--epochs',      type=int,   default=80,        help='number of training epochs')
    parser.add_argument('--lr',          type=float, default=0.01,       help='initial learning rate')
    parser.add_argument('--batch_train', type=int,   default=256,        help='batch size for training')
    parser.add_argument('--data_path',   type=str,   default='data',     help='dataset path')
    parser.add_argument('--save_path',   type=str,   default='result',   help='path to save trained model')
    parser.add_argument('--dsa_strategy',type=str,   default='color_crop_cutout_flip_scale_rotate',     help='DSA strategy (ignored for ImageNet)')
    parser.add_argument('--workers',     type=int,   default=1,          help='dataloader workers (ImageNet only)')
    parser.add_argument('--pretrained',  action='store_true',            help='start from torchvision pretrained weights (ImageNet only)')
    
    # --- New Arguments for Unlearnable Examples ---
    parser.add_argument('--perturb_tensor_filepath', type=str, default='experiments/CIFAR10_samplewise_min-min/perturbation.pt', help='Path to the saved perturbation.pt file')
    parser.add_argument('--perturb_type', type=str, default='samplewise', choices=['samplewise', 'classwise'], help='Type of noise to apply')

    args = parser.parse_args()
    args.device = 'cuda' if torch.cuda.is_available() else 'cpu'

    os.makedirs(args.data_path, exist_ok=True)
    os.makedirs(args.save_path, exist_ok=True)

    print('Hyper-parameters:\n', args.__dict__)

    # ------------------------------------------------------------------
    # All other datasets — use existing utils
    # ------------------------------------------------------------------
    args.dsa_param = ParamDiffAug()
    args.dsa = False if args.dsa_strategy in ['none', 'None'] else True
    args.dc_aug_param = None

    channel, im_size, num_classes, class_names, mean, std, dst_train, dst_test, testloader = \
        get_dataset(args.dataset, args.data_path)

    # --- Apply Unlearnable Noise if Filepath is Provided ---
    if args.perturb_tensor_filepath:
        print(f"Applying {args.perturb_type} noise to the training dataset...")
        dst_train = PoisonedDataset(dst_train, args.perturb_tensor_filepath, args.perturb_type)

    trainloader = torch.utils.data.DataLoader(
        dst_train, batch_size=args.batch_train, shuffle=True, num_workers=args.workers)

    net       = get_network(args.model, channel, num_classes, im_size).to(args.device)
    optimizer = torch.optim.SGD(net.parameters(), lr=args.lr, momentum=0.9, weight_decay=0.0005)
    criterion = nn.CrossEntropyLoss().to(args.device)

    lr_schedule = [args.epochs // 2, args.epochs * 3 // 4]
    current_lr  = args.lr

    print('%s Training %s on full %s for %d epochs' % (get_time(), args.model, args.dataset, args.epochs))

    best_acc = 0.0
    acc_test = 0.0
    for ep in range(1, args.epochs + 1):
        loss_train, acc_train = epoch('train', trainloader, net, optimizer, criterion, args, aug=args.dsa)

        if ep in lr_schedule:
            current_lr *= 0.1
            optimizer = torch.optim.SGD(net.parameters(), lr=current_lr, momentum=0.9, weight_decay=0.0005)
            print('%s LR decayed to %.6f' % (get_time(), current_lr))

        if ep % 10 == 0 or ep == args.epochs:
            loss_test, acc_test = epoch('test', testloader, net, optimizer, criterion, args, aug=False)
            print('%s Epoch %04d/%04d | train loss=%.4f acc=%.4f | test acc=%.4f' % (
                get_time(), ep, args.epochs, loss_train, acc_train, acc_test))

            if acc_test > best_acc:
                best_acc = acc_test
                ckpt = os.path.join(args.save_path, 'noise_model_%s_%s_best.pt' % (args.dataset, args.model))
                torch.save({
                    'epoch': ep,
                    'model_state_dict': net.state_dict(),
                    'acc_test': acc_test,
                    'args': args,
                }, ckpt)
                print('%s Best model saved → %s  (test acc=%.4f)' % (get_time(), ckpt, best_acc))

    ckpt = os.path.join(args.save_path, 'noise_model_%s_%s_final.pt' % (args.dataset, args.model))
    torch.save({
        'epoch': args.epochs,
        'model_state_dict': net.state_dict(),
        'acc_test': acc_test,
        'args': args,
    }, ckpt)
    print('%s Final model saved → %s' % (get_time(), ckpt))
    print('Best test accuracy: %.4f' % best_acc)


if __name__ == '__main__':
    seed = 42
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

    main()